### ISSUE TITLE
Installing Themes in OSX

### ISSUE THREAD

**Issue by scarnago** [IDMComputerSolutions/themes#1]
Please can add instructions about how to add this themes in Mac OS X Yosemite, I can't find how, thanks in advance

**Comment by jcastelli** [comment]
Hi @scarnago – I apologize for the confusion. The Mac and Linux versions of UltraEdit cannot currently be themed, but the feature is under active development. We anticipate this UEX update being released in June, and are currently on track to meet that deadline.

**Comment by scarnago** [comment]
Thanks a lot for this info, because does not appears in any place in your web, or internet... I almost become crazy trying to find an option to add a theme...
